config/routes.rb
Rails.application.routes.draw do
  resources :credits
  resources :genders
  resources :splits
  resources :availabilities
  resources :groups
  resources :group_invites
  resources :group_users
  resources :children


  devise_for :users,
    controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions"}
    #path_names: { sign_in: 'sign_in', sign_out: 'logout', sign_up: 'sign_up'}
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'landing#index'

  get 'dashboard', to: 'landing#dashboard', as: 'dashboard'
  get 'terms_of_service', to: 'landing#terms_of_service', as: 'terms_of_service'
  get 'faq', to: 'landing#faq', as: 'faq'
  get 'my_groups', to: 'groups#my_groups', as: 'my_groups'
  post 'request_split', to: 'splits#request_split', as: 'request_split'
  get 'approve_split/:id', to: 'splits#approve_split', as: 'approve_split'
  get 'decline_split/:id', to: 'splits#decline_split', as: 'decline_split'
  get 'cancel_split/:id', to: 'splits#cancel_split', as: 'cancel_split'
  get 'new_child_onboard', to: 'children#new_onboard', as: 'new_child_onboard'
  post 'create_children_onboard', to: 'children#create_children_onboard', as: 'create_children_onboard'
  get 'group_onboard', to: 'groups#group_onboard', as: 'group_onboard'
  get 'group_code', to: 'groups#group_code', as: 'group_code'
  get 'invite_friends', to: 'groups#invite_friends', as: 'invite_friends'
  post 'invite_friends_on_signup', to: 'groups#invite_friends_on_signup', as: 'invite_friends_on_signup'

  post 'create_group_onboard', to: 'groups#create_group_onboard', as: 'create_group_onboard'
  post 'check_group_code', to: 'groups#check_group_code', as: 'check_group_code'
  post 'join_group_code', to: 'groups#join_group_code', as: 'join_group_code'
  get 'welcome', to: 'landing#welcome_new_user', as: 'welcome_new_user'
  post 'add_bulk_friends', to: 'group_invites#add_bulk_friends', as: 'add_bulk_friends'
  get 'select_group', to: 'groups#select_group', as: 'select_group'
  get 'new_user_onboard', to: 'users#new_user_onboard', as: 'new_user_onboard'
  get 'admin_dash', to: 'users#admin_dash', as: 'admin_dash'
  get 'profile/:id', to: 'users#profile', as: 'profile'
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  before_action :authenticate_active_user, only: [:dashboard, :profile]

  def index
    if user_signed_in?
      redirect_to dashboard_url
    end
  end

  def dashboard
    @page_title = "Splits"
    @group = current_user.groups.first
    if current_user.children.length < 1
      redirect_to new_child_url
      return
    elsif @group === nil
      redirect_to new_group_url
      return
    end
    @availabilities = Availability.where('group_id IN (?) AND start_date >= ?', current_user.groups.pluck(:id),  Date.today-1.days).order(start_date: :asc)
    @bookedSplits = current_user.splits.where('cancelled != ?', true).joins(:availability).where('start_date >= ?', Date.yesterday)
    @hostingSplits = Split.where('splits.availability_id IN (?) AND cancelled != ?', current_user.availabilities.pluck(:id), true).joins(:availability).where('start_date >= ?', Date.yesterday)
  end

  def welcome_new_user
    render :layout => false
  end

  def faq
  end

  def terms_of_service

  end

  def profile
    @user = User.find_by(params[:id])
  end

end

app/views/landing/dashboard.html.erb
<head>
  <!-- Hotjar Tracking Code for http://app.caresplit.com -->
<script>
  (function(h,o,t,j,a,r){
      h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
      h._hjSettings={hjid:1485638,hjsv:6};
      a=o.getElementsByTagName('head')[0];
      r=o.createElement('script');r.async=1;
      r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
      a.appendChild(r);
  })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
</head>
<div class="splitNav">
    <h3 class="splitNavItem selectedSplitNavItem" id="availableNav">Available Sessions</h3>
    <h3 class="splitNavItem" id="bookedNav">Sessions I've booked</h3>
    <h3 class="splitNavItem" id="hostNav">Sessions I'm supervising</h3>
</div>
<div class="availabilityContainer">
  <div class="availableSplitContainer">
    <% @availabilities.each.with_index do |a, index| %>
      <% if(index === 0 || a.start_date.strftime('%^a, %^b %-d') != @availabilities[index-1].start_date.strftime('%^a, %^b %-d'))  %>
        <h1 class="listItemDate"><%= a.start_date.strftime('%^a - %^b %-d') %></h1>
      <% end %>
      <%= render partial: 'availabilities/availability_item', :locals => {availability: a} %>
    <% end %>
  </div>

  <div class="bookedSplitContainer" style="display: none;">
    <% @bookedSplits.each.with_index do |a, index| %>
      <% if(index === 0 || (a.availability.start_date.strftime('%^a, %^b %-d') != @bookedSplits[index-1].availability.start_date.strftime('%^a, %^b %-d')))  %>
        <h1 class="listItemDate"><%= a.availability.start_date.strftime('%^a - %^b %-d') %></h1>
      <% end %>
      <%= render partial: 'availabilities/split_item', :locals => {split: a} %>
    <% end %>
  </div>

  <div class="hostSplitContainer" style="display: none;">
    <% @hostingSplits.each.with_index do |a, index| %>
      <% if(index === 0 || a.availability.start_date.strftime('%^a, %^b %-d') != @hostingSplits[index-1].availability.start_date.strftime('%^a, %^b %-d'))  %>
        <h1 class="listItemDate"><%= a.availability.start_date.strftime('%^a - %^b %-d') %></h1>
      <% end %>
      <%= render partial: 'availabilities/split_item', :locals => {split: a} %>
    <% end %>
  </div>
    <%= link_to new_availability_path do %>
      <div class='bannerBtn'>
        <h3>+ Add My Availability</h3>
      </div>
    <% end %>
</div>

app/views/landing/faq.html.erb
<head>
  <!-- Hotjar Tracking Code for http://app.caresplit.com -->
<script>
  (function(h,o,t,j,a,r){
      h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
      h._hjSettings={hjid:1485638,hjsv:6};
      a=o.getElementsByTagName('head')[0];
      r=o.createElement('script');r.async=1;
      r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
      a.appendChild(r);
  })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
</head>
<div class="pageContainer">
<h2 class="formHeader">FAQ</h2>

<div class="FAQContainer">

  <div class="FAQContainerClosed" id="faq1">
    <h3>What is Caresplit? </h3>
    <div class='faqArrow faqArrowDown'>
      <%= image_tag('chevronDown.svg', id: 'open1') %>
    </div>
    <div class='faqArrow faqArrowUp'>
      <%= image_tag('chevronUp.svg', style: 'display:none;', id: 'close1') %>
    </div>
  </div>
  <div id="content1" style="display:none;">
    <p>We’re a company that’s trying to change childcare forever. We usually connect moms to each other to swap hosting each other’s kids instead of paying a babysitter. But of course, we’re not encouraging in-person playdates because of COVID-19. We’re fully virtual for now - helping all the parents whose children are suddenly home because of school closures.</p>
  </div>
  <div class="FAQContainerClosed" id="faq2">
    <h3>What can I use Caresplit for?</h3>
    <div class='faqArrow faqArrowDown'>
      <%= image_tag('chevronDown.svg', id: 'open2') %>
    </div>
    <div class='faqArrow faqArrowUp'>
      <%= image_tag('chevronUp.svg', style: 'display:none;', id: 'close2') %>
    </div>
  </div>
  <div id="content2" style="display:none;">
    <p>During COVID-19, we’ve moved to a virtual service where another parent can “supervise” your kids while you work from home, shower, get stuff done around the house or care for a loved one.</p>
  </div>
  <div class="FAQContainerClosed" id="faq3">
    <h3>How does it work virtually? </h3>
    <div class='faqArrow faqArrowDown'>
      <%= image_tag('chevronDown.svg', id: 'open3') %>
    </div>
    <div class='faqArrow faqArrowUp'>
      <%= image_tag('chevronUp.svg', style: 'display:none;', id: 'close3') %>
    </div>
  </div>
  <div id="content3" style="display:none;">
    <p>Parents start or join a group of other parents that will use video chat, like FaceTime or Skype to swap supervising homework for each other. While one parent leads reading or science, the other can work from home or get other things done around the house.</p>
  </div>

  <div class="FAQContainerClosed" id="faq4">
    <h3>What is a group? </h3>
    <div class='faqArrow faqArrowDown'>
      <%= image_tag('chevronDown.svg', id: 'open4') %>
    </div>
    <div class='faqArrow faqArrowUp'>
      <%= image_tag('chevronUp.svg', style: 'display:none;', id: 'close4') %>
    </div>
  </div>
  <div id="content4" style="display:none;">
    <p>This is your private community of parents to swap hosting virtual homework sessions with. This could be other parents from your child’s school, church or even family/friends. </p>
  </div>

  <div class="FAQContainerClosed" id="faq5">
      <h3>How do I invite someone to my group? </h3>
      <div class='faqArrow faqArrowDown'>
        <%= image_tag('chevronDown.svg', id: 'open5') %>
      </div>
      <div class='faqArrow faqArrowUp'>
        <%= image_tag('chevronUp.svg', style: 'display:none;', id: 'close5') %>
      </div>
    </div>
    <div id="content5" style="display:none;">
      <p>Under "My Group", you'll see a button that says "Invite a new person". Add the contact info for a parent you think should join your group and trade off video supervision.</p>
    </div>

    <div class="FAQContainerClosed" id="faq6">
      <h3>What happens first? </h3>
      <div class='faqArrow faqArrowDown'>
        <%= image_tag('chevronDown.svg', id: 'open6') %>
      </div>
      <div class='faqArrow faqArrowUp'>
        <%= image_tag('chevronUp.svg', style: 'display:none;', id: 'close6') %>
      </div>
    </div>
    <div id="content6" style="display:none;">
      <p>After you login for the first time and fill out some information about your family, you add your availabilities to help others - dates, times and subjects you can cover. Example: Reading out loud , March 31, 1pm-2pm. You can choose any block of time that works for you, from 30 mins up to a couple of hours.</p>
    </div>
    <div class="FAQContainerClosed" id="faq7">
      <h3>I’ve added when I’m free to supervise someone’s child over video. What next?</h3>
      <div class='faqArrow faqArrowDown'>
        <%= image_tag('chevronDown.svg', id: 'open7') %>
      </div>
      <div class='faqArrow faqArrowUp'>
        <%= image_tag('chevronUp.svg', style: 'display:none;', id: 'close7') %>
      </div>
    </div>
    <div id="content7" style="display:none;">
      <p>Other parents can see when you are free under “Available sessions”. You can also view when they are free and send requests to them for when you need to work or do something around the house. You’ll see how to connect with them via FaceTime or Skype.</p>
    </div>
    <div class="FAQContainerClosed" id="faq8">
      <h3>How can I help other parents who are struggling? </h3>
      <div class='faqArrow faqArrowDown'>
        <%= image_tag('chevronDown.svg', id: 'open8') %>
      </div>
      <div class='faqArrow faqArrowUp'>
        <%= image_tag('chevronUp.svg', style: 'display:none;', id: 'close8') %>
      </div>
    </div>
    <div id="content8" style="display:none;">
      <p>Invite them to your group or send them to www.caresplit.com/virtual. We’re all in this together during this challenging time and can band together to help each other out.</p>
    </div>

  </div>
</div>

<script>
  $(document).on('click', '#faq1', function() {
    console.log('click')
    $('#content1, #open1, #close1, #content1').toggle()

  })
  $(document).on('click', '#faq2', function() {
    console.log('click')
    $('#content2, #open2, #close2, #content2').toggle()
  })
  $(document).on('click', '#faq3', function() {
    console.log('click')
    $('#content3, #open3, #close3, #content3').toggle()

  })
  $(document).on('click', '#faq4', function() {
    console.log('click')
    $('#content4, #open4, #close4, #content4').toggle()

  })
  $(document).on('click', '#faq5', function() {
    console.log('click')
    $('#content5, #open5, #close5, #content5').toggle()

  })
  $(document).on('click', '#faq6', function() {
    console.log('click')
    $('#content6, #open6, #close6, #content6').toggle()

  })
  $(document).on('click', '#faq7', function() {
    console.log('click')
    $('#content7, #open7, #close7, #content7').toggle()

  })
  $(document).on('click', '#faq8', function() {
    console.log('click')
    $('#content8, #open8, #close8, #content8').toggle()

  })
</script>

app/views/landing/index.html.erb
<head>
  <!-- Hotjar Tracking Code for http://app.caresplit.com -->
<script>
  (function(h,o,t,j,a,r){
      h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
      h._hjSettings={hjid:1485638,hjsv:6};
      a=o.getElementsByTagName('head')[0];
      r=o.createElement('script');r.async=1;
      r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
      a.appendChild(r);
  })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
</head>
<div class="mobile hidden">
  <div class="welcomeImageMobile">
  </div>
  <div style="margin: auto; text-align: center;">
    <%= link_to image_tag('logo.png', style:"height: 50px;"), dashboard_path, class:"topNavHeader" %>
    <%= render partial: 'devise/sessions/new' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
    <h5>Need an account? <div class="btnSignUp"><%= link_to "Sign up", new_registration_path(resource_name) %></div>
</div>
</div>
</div>

<div class="desktop">
  <div class="welcomeImageDesktop">
    <div style="margin: auto; text-align: center;">
      <%= link_to image_tag('logo.png', style:"height: 50px;"), dashboard_path, class:"topNavHeader" %>
      <%= render partial: 'devise/sessions/new' %>
      <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
      <h5>Need an account? <%= link_to "Sign up", new_registration_path(resource_name) %></h5>
    </div>
  </div>
</div>

<script>
$(window).on("load resize", function() {
      if ($(window).width() > 600) {
        $(".mobile").addClass('hidden');
        $(".desktop").removeClass('hidden');
      } else {
        $(".desktop").addClass('hidden');
        $(".mobile").removeClass('hidden');
      }
});

</script>

app/views/landing/profile.html.erb
<h1><%= @user.first_name %></h1>

Children:
<% @user.children.each do |child| %>
  <div>
    <h3><%= child.first_name %></h3>
    <h3><%= child.birthday %></h3>
    <h3><%= child.notes %></h3>
  </div>
<% end %>

app/views/landing/terms_of_service.html.erb
<head>
  <!-- Hotjar Tracking Code for http://app.caresplit.com -->
<script>
  (function(h,o,t,j,a,r){
      h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
      h._hjSettings={hjid:1485638,hjsv:6};
      a=o.getElementsByTagName('head')[0];
      r=o.createElement('script');r.async=1;
      r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
      a.appendChild(r);
  })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
</head>
<div class="pageContainer">
<h2 class="formHeader">FAQ</h2>
<div class="FAQContainer">
  <div class="FAQContainerClosed" id="faq1">
    <h3>What is Caresplit?</h3>
    <div class='faqArrow faqArrowDown'>
      <%= image_tag('chevronDown.svg', id: 'open1') %>
    </div>
    <div class='faqArrow faqArrowUp'>
      <%= image_tag('chevronUp.svg', style: 'display:none;', id: 'close1') %>
    </div>
    <div id="content1" style="display:none;">
      <p>We're a company that's trying to change childcare forever. We usually connect moms to each other to swap hosting each other's kids instead of paying a babysitter. But of course, we're not encouraging in-person playdates because of COVID-19. We're fully virtual for now - helping all the parents whose children are suddenly home because of school closures.</p>
    </div>
  </div>
</div>
<script>
  $(document).on('click', '#faq1', function() {
    console.log('click')
    $('#content1, #open1, #close1, #content1').toggle()
  })
  $(document).on('click', '#faq2', function() {
    console.log('click')
    $('#content2, #open2, #close2, #content2').toggle()
  })
  $(document).on('click', '#faq3', function() {
    console.log('click')
    $('#content3, #open3, #close3, #content3').toggle()
  })
  $(document).on('click', '#faq4', function() {
    console.log('click')
    $('#content4, #open4, #close4, #content4').toggle()
  })
  $(document).on('click', '#faq5', function() {
    console.log('click')
    $('#content5, #open5, #close5, #content5').toggle()
  })
  $(document).on('click', '#faq6', function() {
    console.log('click')
    $('#content6, #open6, #close6, #content6').toggle()
  })
  $(document).on('click', '#faq7', function() {
    console.log('click')
    $('#content7, #open7, #close7, #content7').toggle()
  })
  $(document).on('click', '#faq8', function() {
    console.log('click')
    $('#content8, #open8, #close8, #content8').toggle()
  })
</script>

app/views/landing/welcome_new_user.html.erb
<!DOCTYPE html>
<html style="height: 100%;">
  <head>
    <title>Caresplit</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Hotjar Tracking Code for http://app.caresplit.com -->
  <script>
      (function(h,o,t,j,a,r){
          h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
          h._hjSettings={hjid:1485638,hjsv:6};
          a=o.getElementsByTagName('head')[0];
          r=o.createElement('script');r.async=1;
          r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
          a.appendChild(r);
      })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
  </script>
</head>

  <body class="welcomePage">
    <div>
        <h1 style="width: 341px;
          height: 142px;
          font-family: Cabin;
          font-size: 58px;
          color: #ffffff;
          font-weight: 700;
          text-decoration: none solid rgb(255, 255, 255);
          text-align: center;
          text-shadow: 0px 1px 60px rgba(0,0,0,0.8);
          margin: auto;
          margin-top: 40%;">Welcome <%= current_user.first_name %>!</h1>
    </div>
    <script>
      setTimeout(function(){ window.location = '/dashboard' }, 2000);
    </script>
  </body>

</html>