config/routes.rb
Rails.application.routes.draw do
  resources :credits
  resources :genders
  resources :splits
  resources :availabilities
  resources :groups
  resources :group_invites
  resources :group_users
  resources :children


  devise_for :users,
    controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions"}
    #path_names: { sign_in: 'sign_in', sign_out: 'logout', sign_up: 'sign_up'}
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'landing#index'

  get 'dashboard', to: 'landing#dashboard', as: 'dashboard'
  get 'terms_of_service', to: 'landing#terms_of_service', as: 'terms_of_service'
  get 'faq', to: 'landing#faq', as: 'faq'
  get 'my_groups', to: 'groups#my_groups', as: 'my_groups'
  post 'request_split', to: 'splits#request_split', as: 'request_split'
  get 'approve_split/:id', to: 'splits#approve_split', as: 'approve_split'
  get 'decline_split/:id', to: 'splits#decline_split', as: 'decline_split'
  get 'cancel_split/:id', to: 'splits#cancel_split', as: 'cancel_split'
  get 'new_child_onboard', to: 'children#new_onboard', as: 'new_child_onboard'
  post 'create_children_onboard', to: 'children#create_children_onboard', as: 'create_children_onboard'
  get 'group_onboard', to: 'groups#group_onboard', as: 'group_onboard'
  get 'group_code', to: 'groups#group_code', as: 'group_code'
  get 'invite_friends', to: 'groups#invite_friends', as: 'invite_friends'
  post 'invite_friends_on_signup', to: 'groups#invite_friends_on_signup', as: 'invite_friends_on_signup'

  post 'create_group_onboard', to: 'groups#create_group_onboard', as: 'create_group_onboard'
  post 'check_group_code', to: 'groups#check_group_code', as: 'check_group_code'
  post 'join_group_code', to: 'groups#join_group_code', as: 'join_group_code'
  get 'welcome', to: 'landing#welcome_new_user', as: 'welcome_new_user'
  post 'add_bulk_friends', to: 'group_invites#add_bulk_friends', as: 'add_bulk_friends'
  get 'select_group', to: 'groups#select_group', as: 'select_group'
  get 'new_user_onboard', to: 'users#new_user_onboard', as: 'new_user_onboard'
  get 'admin_dash', to: 'users#admin_dash', as: 'admin_dash'
  get 'profile/:id', to: 'users#profile', as: 'profile'
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :availabilities

  belongs_to :creator, :foreign_key => :creator_id, class_name: 'User'
  validates_uniqueness_of :name
  validates_uniqueness_of :code
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_active_user
  before_action :authenticate_admin, only: [:index]
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_group_user, except: [:index, :new, :create, :my_groups, :group_onboard, :create_group_onboard, :select_group, :group_code, :check_group_code, :invite_friends, :invite_friends_on_signup, :join_group_code]

  include SmsHelper
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  def select_group

  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  def my_groups
    @groups = current_user.groups
    @group_user = GroupUser.new
  end

  def group_onboard
    @group = current_user.groups.first
    @group_users = @group.users.first(3)
  end

  def group_code
    @group_user = GroupUser.new
  end

  def create_group_onboard
    #create group
    if params[:group][:name] != ''
      @group = Group.new(name: params[:group][:name], creator_id: current_user.id)
      generate_group_code(@group)
      if @group.save
        #make current user group admin
        puts 'create group onboard'
        GroupUser.create(user_id: current_user.id, group_id: @group.id, admin: true)
        GroupMailer.confirm_new_group(@group.id, current_user.id).deliver_later
        respond_to do |format|
            format.html { redirect_to invite_friends_url }
            format.json { head :no_content }
        end

      else
        respond_to do |format|
          format.html { redirect_to new_group_url, alert: 'This group name is already taken.' }
          format.json { render json: @group.errors, status: :unprocessable_entity }
        end
        return
      end
    else
      respond_to do |format|
        format.html { redirect_to new_group_url, alert: 'Please provide a name for the group.' }
        format.json { render json: {}, status: :unprocessable_entity }
      end
      return
    end
  end

  def invite_friends
    @group = current_user.groups.last
  end

  def invite_friends_on_signup
    @group = current_user.groups.last
    params[:group_user].each do |user|
      if(user[:email] != nil && user[:email] != '')
        @group_invite = GroupInvite.new(email: user[:email], group_id: @group.id, user_id: current_user.id)
        if @group_invite.save
          #email group invitees
          GroupInviteMailer.send_invite(@group_invite.id).deliver_later
        end
      elsif(user[:phone] != nil && user[:phone] != '')
        @group_invite = GroupInvite.new(phone: user[:phone], group_id: @group.id, user_id: current_user.id)
        if @group_invite.save
          #sms group invitees
          @message = " You’ve been invited to join Caresplit- your support network of other parents to swap hosting virtual activities with during school closures. Create your profile and get started here: app.caresplit.com/users/sign_up"
          #@message = "Hey it’s #{@group_invite.invitee.first_name}! Join my Caresplit group, #{@group.name}. We can split childcare - it’s free! Here’s the link: app.caresplit.com/users/sign_up"
          invite_sms(@group_invite.phone, @message)
        end
      end

    end
    redirect_to new_user_onboard_path
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def check_group_code
    code = params[:group_user][:code].upcase.strip
    @group = Group.find_by(code: code)

    respond_to do |format|
      if code.length != 4
          format.html { redirect_to group_code_url, alert: 'Please enter your 4 digit code' }
          format.json { head :no_content }
      elsif @group === nil
          format.html { redirect_to group_code_url, alert: 'That code does not match any groups.' }
          format.json { head :no_content }
      else
        @group_user = GroupUser.new(user_id: current_user.id, group_id: @group.id)
        @group_user.save
        format.html { redirect_to group_onboard_url }
        format.json { head :no_content }
      end
    end
  end

  def join_group_code
    code = params[:group_user][:code].upcase.strip
    @group = Group.find_by(code: code)

    respond_to do |format|
      if @group === nil
          format.html { redirect_to my_groups_url, alert: 'That code does not match any groups.' }
          format.json { head :no_content }
      else
        @group_user = GroupUser.new(user_id: current_user.id, group_id: @group.id)
        @group_user.save
        notice = 'You joined ' + @group.name + ''
        format.html { redirect_to my_groups_url, notice: notice }
        format.json { head :no_content }
      end
    end
  end

  def create
    @group = Group.new(group_params)

    @group.creator = current_user
    generate_group_code(@group)

    respond_to do |format|
      if @group.save
        GroupUser.create(user_id: current_user.id, group_id: @group.id, admin: true)
        GroupMailer.confirm_new_group(@group.id, current_user.id).deliver_now
        @notice = 'Now lets invite your mom friends to ' + @group.name + '!'
        format.html { redirect_to group_invites_url, notice: @notice}
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    def authenticate_group_user
      if !current_user.groups.pluck(:id).include? @group.id
        redirect_to dashboard_path, error: 'You are not in that group.'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :creator, :notes, :code)
    end

    def generate_group_code(group)
       code = SecureRandom.hex(2).upcase
       if Group.find_by(code: code) != nil
         code = SecureRandom.hex(2).upcase
         if Group.find_by(code: code) != nil
           code = SecureRandom.hex(2).upcase
           if Group.find_by(code: code) != nil
             code = SecureRandom.hex(2).upcase
           end
         end
       end
       group.code = code
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="pageContainer">
  <h2 class="signUpHeader">New Group</h2>
    <div class="formStandard">
    <%= form_for(group) do |f| %>
      <% if group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

          <ul>
          <% group.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label 'NAME', class: "labelStandard" %>
        <%= f.text_field :name, class: "inputStandard" %>
      </div>
      


      <!-- <div class="field">
        <%#= f.label :notes %>
        <%#= f.text_area :notes %>
      </div> -->

      <div class="actions">
        <%= f.submit, class: "btnPrimary btnPrimaryLarge" %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/group_code.html.erb
<div class="pageContainer">
  <div class="formStandard">
    <div class="signUpProgress">
      <%= image_tag('line.svg', style: "z-index: 100;") %>
      <div class="dotContainer">
        <div class="dot greyDot"></div>
        <div class="dot purpleDot"></div>
        <div class="dot greyDot"></div>
        <div class="dot greyDot"></div>
        <div class="dot greyDot"></div>
      </div>
    </div>

  <h1 class="signUpHeading">Enter your group code:</h1>
    <%= form_for(@group_user, url: check_group_code_url, html: { method: :post }) do |f| %>
        <% if @group_user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@group_user.errors.count, "error") %> Something went wrong!</h2>

            <ul>
            <% @group_user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.text_field :code, class: "inputStandard" %>
        </div>

        <div class="actions">
          <%= f.submit "Join Group", class: 'btnPrimary btnPrimaryLarge' %>
        </div>
      <% end %>
    <div>
    </div>
  </div>
</div>

app/views/groups/group_onboard.html.erb
<div class="pageContainer">
  <div class="formStandard">
    <div class="signUpProgress">
      <%= image_tag('line.svg', style: "z-index: 100;") %>
      <div class="dotContainer">
        <div class="dot greyDot"></div>
        <div class="dot greyDot"></div>
        <div class="dot pinkDot"></div>
        <div class="dot greyDot"></div>
        <div class="dot greyDot"></div>
      </div>
    </div>
    <h2 class="signUpHeader">You are joining the split group<br/>"<%= @group.name %>"</h2>

    <h3 class="inFormInstructions">Current Members:</h3>

    <div class="groupMemberContainer">
      <% @group_users.each do |user| %>
        <div class="groupMember">
          <%= image_tag(image_url(user.photo(:thumb)), class: 'splitImage') %>
          <h3><%= user.first_name %></h3>
        </div>
      <% end %>
    </div>
    <div class="formStandard">
      <h3 class="inFormInstructions">Want to invite more mom friends to this group?</h3>
      <%= form_tag({:action => 'add_bulk_friends', :controller=>"group_invites"}) do %>
        <div id="user_form" >
          <div class="field">
            <h3>PHONE NUMBER</h3>
            <%= text_field_tag 'group_user[][phone]', '', class: "inputStandard", id: 'phoneNumber' %>
          </div>
          <div class="field" style="margin-top: 15px;">
            <h3>EMAIL</h3>
            <%= text_field_tag 'group_user[][email]', '', class: "inputStandard" %>
          </div>
        </div>
        <div id="new_user_form" style="display:none;" >
          <div class="field" style="margin-top: 15px;">
            <h3>PHONE NUMBER</h3>
            <%= text_field_tag 'group_user[][phone]', '', class: "inputStandard", id: 'phoneNumber' %>
          </div>
          <div class="field" style="margin-top: 15px;">
            <h3>EMAIL</h3>
            <%= text_field_tag 'group_user[][email]', '', class: "inputStandard" %>
          </div>
        </div>
        <div class="subActions">
          <button id="add_group_user" class='darkBtnPrimary'>+ Add Another</button>
        </div>
        <div class="actions">
          <%= submit_tag "Next", class: 'btnPrimary btnPrimaryLarge' %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<script>
  $('#add_group_user').bind('click', function(e) {
      e.preventDefault();
      var row = $('#new_user_form').clone()
      $('#user_form').append(row.removeAttr("id").toggle())
  });
</script>

app/views/groups/index.html.erb
<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Creator</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.creator %></td>
        <td><%= group.notes %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/invite_friends.html.erb
<div class="pageContainer">
  <h2 class="formHeader">Congrats! You've created a group called <%= @group.name %></h2>
  <h2 class="formHeader" style="padding-top: 20px; font-weight: 300;">Your private invitation code is:</h2>
  <h2 class="formHeader" style="padding: 10px; font-size: 32px; font-weight: 700;"><%= @group.code %></h2>

  <div class="formStandard">
    <div class="signUpProgress">
      <%= image_tag('line.svg', style: "z-index: 100;") %>
      <div class="dotContainer">
        <div class="dot greyDot"></div>
        <div class="dot greyDot"></div>
        <div class="dot purpleDot"></div>
        <div class="dot greyDot"></div>
        <div class="dot greyDot"></div>
      </div>
    </div>
    <%= form_tag({:action => 'invite_friends_on_signup'}) do %>

      <h3 class="inFormInstructions">Add parents you'd like to invite.</h3>

      <div id="user_form" class="field">
        <h3>PHONE</h3>
        <%= text_field_tag 'group_user[][phone]', '', class: "inputStandard",  id: 'phoneNumber' %>
        <h3>EMAIL</h3>
        <%= text_field_tag 'group_user[][email]', '', class: "inputStandard" %>
      </div>

      <div id="new_user_form" class="field" style="display:none; margin-top: 15px;">
        <h3>PHONE</h3>
        <%= text_field_tag 'group_user[][phone]', '', class: "inputStandard",  id: 'phoneNumber', style: "width: 100%" %>
        <h3>EMAIL</h3>
        <%= text_field_tag 'group_user[][email]', '', class: "inputStandard", style: "width: 100%" %>
      </div>
      <div class="subActions">
        <button id="add_group_user" class='darkBtnPrimary'>+ Add Another</button>
      </div>
      <div class="actions">
        <%= submit_tag "Continue", class: 'btnPrimary btnPrimaryLarge' %>
      </div>
    <% end %>
  </div>
</div>


<script>
  $('#add_group_user').bind('click', function(e) {
      e.preventDefault();
      var row = $('#new_user_form').clone()
      $('#user_form').append(row.removeAttr("id").toggle())
  });
</script>

app/views/groups/my_groups.html.erb
<h1 class="pageTitle">My Group</h1>
<div class="pageContainer">
  <% @groups.each do |g| %>
    <h1 class="pageTitle" style="text-align: center;"><%= g.name %></h1>
    <div style="text-align: center;">
      <h1 class="pageTitle" style="text-align: center; display: inline-block">Group Code: </h1>
      <h1 class="pageTitle" style="text-align: center; display: inline-block; font-size: 28px;"><%= g.code %></h1>
    </div>
    <div class="groupMemberContainer">
      <% g.users.each do |user| %>
        <div class="groupMember">
          <%= link_to profile_path(user) do %>
            <%= image_tag(image_url(user.photo(:thumb)), class: 'splitImage') %>
            <h3><%= user.first_name %></h3>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
  <%= link_to 'Invite a new person', new_group_invite_path, class: 'btnPrimary btnPrimaryLarge', style: "width: 100%" %>
  <%= link_to 'Start a new Group', new_group_path, class: 'btnSecondary btnPrimaryLarge', style: "margin-top: 20px; width: 100%" %>
  <div>
    <%= form_for(@group_user, url: join_group_code_url, html: { method: :post }) do |f| %>
        <% if @group_user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@group_user.errors.count, "error") %> Something went wrong!</h2>

            <ul>
            <% @group_user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div style="display: flex; padding: 20px 0;">
          <%= f.text_field :code, class: "inputStandard", placeholder: 'XXXX', style: "margin-right: 15px;" %>
          <%= f.submit "Join Group", class: 'btnPrimary btnPrimaryLarge' %>
        </div>
      <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="pageContainer">
  <h2 class="formHeader">Now let's start a group with other parents from school!</h2>
  <div class="formStandard">
    <div class="signUpProgress">
      <%= image_tag('line.svg', style: "z-index: 100;") %>
      <div class="dotContainer">
        <div class="dot greyDot"></div>
        <div class="dot purpleDot"></div>
        <div class="dot greyDot"></div>
        <div class="dot greyDot"></div>
        <div class="dot greyDot"></div>
      </div>
    </div>
    <%= form_tag({:action => 'create_group_onboard'}) do %>
      <div class="field">
        <h3>Group Name (Example: "Mrs. Brown's third grade class")</h3>
        <%= text_field_tag 'group[name]', '', options={class: "inputStandard"} %>
      </div>
      <div class="actions">
        <%= submit_tag "Continue", class: 'btnPrimary btnPrimaryLarge' %>
      </div>
    <% end %>
  </div>
</div>


<script>
  $('#add_group_user').bind('click', function(e) {
      e.preventDefault();
      var row = $('#new_user_form').clone()
      $('#user_form').append(row.removeAttr("id").toggle())
  });
</script>

app/views/groups/select_group.html.erb
<div class="pageContainer">
  <div class="formStandard">
    <div class="signUpProgress">
      <%= image_tag('line.svg', style: "z-index: 100;") %>
      <div class="dotContainer">
        <div class="dot greyDot"></div>
        <div class="dot purpleDot"></div>
        <div class="dot greyDot"></div>
        <div class="dot greyDot"></div>
        <div class="dot greyDot"></div>
      </div>
    </div>

    <h1 class="signUpHeading">Do you have an invitation code to join a group?</h1>
    <div>
      <%= link_to("I have a group code", group_code_path, class: "btnPrimary btnPrimaryLarge", style: "margin: auto; margin-top: 50px; width: unset;" ) %>
      <%= link_to("Create a new group", new_group_path, class: "btnSecondary btnPrimaryLarge", style: "margin: auto; margin-top: 50px;" ) %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @group.creator %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @group.notes %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>