config/routes.rb
Rails.application.routes.draw do
  resources :credits
  resources :genders
  resources :splits
  resources :availabilities
  resources :groups
  resources :group_invites
  resources :group_users
  resources :children


  devise_for :users,
    controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions"}
    #path_names: { sign_in: 'sign_in', sign_out: 'logout', sign_up: 'sign_up'}
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'landing#index'

  get 'dashboard', to: 'landing#dashboard', as: 'dashboard'
  get 'terms_of_service', to: 'landing#terms_of_service', as: 'terms_of_service'
  get 'faq', to: 'landing#faq', as: 'faq'
  get 'my_groups', to: 'groups#my_groups', as: 'my_groups'
  post 'request_split', to: 'splits#request_split', as: 'request_split'
  get 'approve_split/:id', to: 'splits#approve_split', as: 'approve_split'
  get 'decline_split/:id', to: 'splits#decline_split', as: 'decline_split'
  get 'cancel_split/:id', to: 'splits#cancel_split', as: 'cancel_split'
  get 'new_child_onboard', to: 'children#new_onboard', as: 'new_child_onboard'
  post 'create_children_onboard', to: 'children#create_children_onboard', as: 'create_children_onboard'
  get 'group_onboard', to: 'groups#group_onboard', as: 'group_onboard'
  get 'group_code', to: 'groups#group_code', as: 'group_code'
  get 'invite_friends', to: 'groups#invite_friends', as: 'invite_friends'
  post 'invite_friends_on_signup', to: 'groups#invite_friends_on_signup', as: 'invite_friends_on_signup'

  post 'create_group_onboard', to: 'groups#create_group_onboard', as: 'create_group_onboard'
  post 'check_group_code', to: 'groups#check_group_code', as: 'check_group_code'
  post 'join_group_code', to: 'groups#join_group_code', as: 'join_group_code'
  get 'welcome', to: 'landing#welcome_new_user', as: 'welcome_new_user'
  post 'add_bulk_friends', to: 'group_invites#add_bulk_friends', as: 'add_bulk_friends'
  get 'select_group', to: 'groups#select_group', as: 'select_group'
  get 'new_user_onboard', to: 'users#new_user_onboard', as: 'new_user_onboard'
  get 'admin_dash', to: 'users#admin_dash', as: 'admin_dash'
  get 'profile/:id', to: 'users#profile', as: 'profile'
end

app/models/split.rb
class Split < ApplicationRecord
  belongs_to :availability
  belongs_to :user

  validates_uniqueness_of :availability, :scope => :user
  has_many :split_children
  has_many :children, through: :split_children
end

app/controllers/splits_controller.rb
class SplitsController < ApplicationController
  before_action :authenticate_active_user
  before_action :authenticate_admin, only: [:index, :destroy]
  before_action :set_split, only: [:show, :edit, :update, :destroy, :approve_split, :decline_split, :cancel_split]
  before_action :authenticate_split_user, only: [:show, :view, :edit, :approve_split, :decline_split, :cancel_split ]
  include SmsHelper
  # GET /splits
  # GET /splits.json
  def index
    @splits = Split.all
  end

  # GET /splits/1
  # GET /splits/1.json
  def show
    @credits = (@split.availability.end_time.to_i - @split.availability.start_time.to_i)/3600
  end

  # GET /splits/new
  def new
    @split = Split.new
  end

  # GET /splits/1/edit
  def edit
  end

  def request_split
    @children = params[:child]
    @id = params[:availability][:id]

    @split = Split.new(availability_id: @id, user_id: current_user.id, approved: false)
    @credits = (@split.availability.end_time.to_i - @split.availability.start_time.to_i)/3600
    @notes = "Booked " + @split.availability.user.first_name + " " + @split.availability.user.last_name[0] + "."
    respond_to do |format|
      if @children === nil
        format.html { redirect_to availability_path(@id), alert: 'You did not select any children for the split!' }
        format.json { render json: @split.errors, status: :unprocessable_entity }
      elsif @split.save
        @child_count = 0
        @children.each do |child|
          @child_count += 1
          SplitChild.create(split_id: @split.id, child_id: child)
        end

        adjust_credits(@split.id, current_user.id, false, @credits, @notes)
        #send sms to mom being requested.
        #request_split_sms(@split.id)
        SplitMailer.request_availability(@split.id).deliver_later
        format.html { redirect_to dashboard_path, notice: 'Split was requested!' }
        format.json { render :show, status: :created, location: @split }
      else
        format.html { redirect_to availability_path(@id), alert: 'Something went wrong!' }
        format.json { render json: @split.errors, status: :unprocessable_entity }
      end
    end
  end

  def approve_split
    @split.approved = true
    @credits = (@split.availability.end_time.to_i - @split.availability.start_time.to_i)/3600
    @notes = "Hosted " + @split.user.first_name + " " + @split.user.last_name[0] + "."

    #todo - mail approved email
    # todo - create notification

    respond_to do |format|
      if @split.save
        #give credits to user who requested split
        adjust_credits(@split.id, current_user.id, true, @credits, @notes)
        #approve_split_sms(@split.id)
        #mailer
        SplitMailer.confirm_split_availability_user(@split.id).deliver_later
        SplitMailer.confirm_split_split_user(@split.id).deliver_later

        format.html { redirect_to dashboard_path, notice: 'Split was approved!' }
        format.json { render :show, status: :created, location: @split }
      else
        format.html { render :new }
        format.json { render json: @split.errors, status: :unprocessable_entity }
      end
    end
  end

  def decline_split
    @split.approved = false
    @split.cancelled = true
    @credits = (@split.availability.end_time.to_i - @split.availability.start_time.to_i)/3600


    #todo - mail decline email
    # todo - create notification

    respond_to do |format|
      if @split.save
        #credit back person who booked split.
        @user = @split.user
        @notes = "" + @split.availability.user.first_name + " " + @split.availability.user.last_name[0] + " cancelled the split."
        adjust_credits(@split.id, @user.id, true, @credits, @notes)

        format.html { redirect_to dashboard_path, notice: 'Split was cancelled.' }
        format.json { render :show, status: :created, location: @split }
      else
        format.html { render :new }
        format.json { render json: @split.errors, status: :unprocessable_entity }
      end
    end
  end

  def cancel_split
    @split.cancelled = true
    #todo - mail cancelled email
    # todo - create notification

    @credits = (@split.availability.end_time.to_i - @split.availability.start_time.to_i)/3600
    @notes = "Split was cancelled."

    respond_to do |format|
      if @split.save
        #credit back person who booked split.
        adjust_credits(@split.id, @split.user.id, true, @credits, @notes)

        #subtract credits from person who was hosting
        adjust_credits(@split.id, @split.availability.user.id, false, @credits, @notes)

        format.html { redirect_to dashboard_path, notice: 'Split was approved!' }
        format.json { render :show, status: :created, location: @split }
      else
        format.html { render :new }
        format.json { render json: @split.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /splits
  # POST /splits.json
  def create
    @split = Split.new(split_params)

    respond_to do |format|
      if @split.save
        format.html { redirect_to @split, notice: 'Split was successfully created.' }
        format.json { render :show, status: :created, location: @split }
      else
        format.html { render :new }
        format.json { render json: @split.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /splits/1
  # PATCH/PUT /splits/1.json
  def update
    respond_to do |format|
      if @split.update(split_params)
        format.html { redirect_to @split, notice: 'Split was successfully updated.' }
        format.json { render :show, status: :ok, location: @split }
      else
        format.html { render :edit }
        format.json { render json: @split.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /splits/1
  # DELETE /splits/1.json
  def destroy
    @split.destroy
    respond_to do |format|
      format.html { redirect_to splits_url, notice: 'Split was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_split
      @split = Split.find(params[:id])
    end

    def authenticate_split_user
      if((@split.user_id != current_user.id && @split.availability.user_id != current_user.id))
        redirect_to dashboard_path, alert: 'You do not have access to that Split'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def split_params
      params.require(:split).permit(:availability_id, :user_id, :approved, :cancelled)
    end
end

app/helpers/splits_helper.rb
module SplitsHelper
end

app/views/splits/_form.html.erb
<%= form_for(split) do |f| %>
  <% if split.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(split.errors.count, "error") %> prohibited this split from being saved:</h2>

      <ul>
      <% split.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :availability_id %>
    <%= f.text_field :availability_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :approved %>
    <%= f.check_box :approved %>
  </div>

  <div class="field">
    <%= f.label :cancelled %>
    <%= f.check_box :cancelled %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/splits/edit.html.erb
<h1>Editing Split</h1>

<%= render 'form', split: @split %>

<%= link_to 'Show', @split %> |
<%= link_to 'Back', splits_path %>

app/views/splits/index.html.erb
<h1>Splits</h1>

<table>
  <thead>
    <tr>
      <th>Availability</th>
      <th>User</th>
      <th>Approved</th>
      <th>Cancelled</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @splits.each do |split| %>
      <tr>
        <td><%= split.availability %></td>
        <td><%= split.user %></td>
        <td><%= split.approved %></td>
        <td><%= split.cancelled %></td>
        <td><%= link_to 'Show', split %></td>
        <td><%= link_to 'Edit', edit_split_path(split) %></td>
        <td><%= link_to 'Destroy', split, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Split', new_split_path %>

app/views/splits/new.html.erb
<h1>New Split</h1>

<%= render 'form', split: @split %>

<%= link_to 'Back', splits_path %>

app/views/splits/show.html.erb
<div class="formStandard">
  <div class="splitHeader">
    <div class="splitImageSection">
      <%= image_tag(image_url(@split.availability.user.photo(:thumb)), class: 'splitImage') %>
      <h3><%= formatUserName(@split.availability.user) %></h3>
    </div>
    <div>
      <!-- <%#= @credits %> CREDITS -->
    </div>
  </div>
  <div class="splitInfo">
    <h3 class="labelStandard">DATE</h3>
    <h3><%= @split.availability.start_date.strftime('%d/%m/%Y') %></h3>
  </div>
  <div class="splitInfo">
    <h3 class="labelStandard">START TIME</h3>
    <h3><%= @split.availability.start_time.strftime('%l:%M %p') %></h3>
  </div>
  <div class="splitInfo">
    <h3 class="labelStandard">END TIME</h3>
    <h3><%= @split.availability.end_time.strftime('%l:%M %p') %></h3>
  </div>
  <div class="splitInfo">
    <h3 class="labelStandard">ACTIVITY</h3>
    <h3><%= @split.availability.activity %></h3>
  </div>
  <div class="splitInfo">
    <h3 class="labelStandard">NOTES</h3>
    <h3><%= @split.availability.activity %></h3>
  </div>
  <div class="splitInfo">
    <h3 class="labelStandard">LOCATION</h3>
    <h3><%= @split.availability.location %></h3>
    <h3><%= @split.availability.location_address %></h3>
  </div>
  <div class="actions">
    <% if (@split.availability.user_id === current_user.id) && !@split.approved && !@split.cancelled %>
        <%= link_to('Approve Split', approve_split_path(@split), class: 'btnPrimary btnPrimarySmall') %>
        <%= link_to('Decline Split', decline_split_path(@split), class: 'btnSecondarySmall') %>
    <% elsif  @split.approved && !@split.cancelled %>
        <%= link_to('Cancel Split', cancel_split_path(@split), class: 'btnSecondarySmall') %>
    <% end %>
  </div>
</div>