config/routes.rb
Rails.application.routes.draw do
  resources :credits
  resources :genders
  resources :splits
  resources :availabilities
  resources :groups
  resources :group_invites
  resources :group_users
  resources :children


  devise_for :users,
    controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions"}
    #path_names: { sign_in: 'sign_in', sign_out: 'logout', sign_up: 'sign_up'}
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'landing#index'

  get 'dashboard', to: 'landing#dashboard', as: 'dashboard'
  get 'terms_of_service', to: 'landing#terms_of_service', as: 'terms_of_service'
  get 'faq', to: 'landing#faq', as: 'faq'
  get 'my_groups', to: 'groups#my_groups', as: 'my_groups'
  post 'request_split', to: 'splits#request_split', as: 'request_split'
  get 'approve_split/:id', to: 'splits#approve_split', as: 'approve_split'
  get 'decline_split/:id', to: 'splits#decline_split', as: 'decline_split'
  get 'cancel_split/:id', to: 'splits#cancel_split', as: 'cancel_split'
  get 'new_child_onboard', to: 'children#new_onboard', as: 'new_child_onboard'
  post 'create_children_onboard', to: 'children#create_children_onboard', as: 'create_children_onboard'
  get 'group_onboard', to: 'groups#group_onboard', as: 'group_onboard'
  get 'group_code', to: 'groups#group_code', as: 'group_code'
  get 'invite_friends', to: 'groups#invite_friends', as: 'invite_friends'
  post 'invite_friends_on_signup', to: 'groups#invite_friends_on_signup', as: 'invite_friends_on_signup'

  post 'create_group_onboard', to: 'groups#create_group_onboard', as: 'create_group_onboard'
  post 'check_group_code', to: 'groups#check_group_code', as: 'check_group_code'
  post 'join_group_code', to: 'groups#join_group_code', as: 'join_group_code'
  get 'welcome', to: 'landing#welcome_new_user', as: 'welcome_new_user'
  post 'add_bulk_friends', to: 'group_invites#add_bulk_friends', as: 'add_bulk_friends'
  get 'select_group', to: 'groups#select_group', as: 'select_group'
  get 'new_user_onboard', to: 'users#new_user_onboard', as: 'new_user_onboard'
  get 'admin_dash', to: 'users#admin_dash', as: 'admin_dash'
  get 'profile/:id', to: 'users#profile', as: 'profile'
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :user
  has_many :splits
  belongs_to :group
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :authenticate_active_user
  before_action :authenticate_admin, only: [:index, :destroy]

  before_action :set_availability, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_group_user, only: [:show, :view, :edit]

  # GET /availabilities
  # GET /availabilities.json
  def index
    @availabilities = current_user.availabilities
  end

  # GET /availabilities/1
  # GET /availabilities/1.json
  def show
    @credits = (@availability.end_time.to_i - @availability.start_time.to_i)/3600
    @children = current_user.children
  end

  # GET /availabilities/new
  def new
    @availability = Availability.new
    @time_select_options = ['12:00 AM', '12:15 AM', '12:30 AM', '12:45 AM', '1:00 AM', '1:15 AM', '1:30 AM', '1:45 AM', '2:00 AM', '2:15 AM', '2:30 AM', '2:45 AM', '3:00 AM', '3:15 AM', '3:30 AM', '3:45 AM', '4:00 AM', '4:15 AM', '4:30 AM', '4:45 AM', '5:00 AM', '5:15 AM', '5:30 AM', '5:45 AM', '6:00 AM', '6:15 AM', '6:30 AM', '6:45 AM', '7:00 AM', '7:15 AM', '7:30 AM', '7:45 AM', '8:00 AM', '8:15 AM', '8:30 AM', '8:45 AM', '9:00 AM', '9:15 AM', '9:30 AM', '9:45 AM', '10:00 AM', '10:15 AM', '10:30 AM', '10:45 AM', '11:00 AM', '11:15 AM', '11:30 AM', '11:45 AM', '12:00 PM', '12:15 PM', '12:30 PM', '12:45 PM', '1:00 PM', '1:15 PM', '1:30 PM', '1:45 PM', '2:00 PM', '2:15 PM', '2:30 PM', '2:45 PM', '3:00 PM', '3:15 PM', '3:30 PM', '3:45 PM', '4:00 PM', '4:15 PM', '4:30 PM', '4:45 PM', '5:00 PM', '5:15 PM', '5:30 PM', '5:45 PM', '6:00 PM', '6:15 PM', '6:30 PM', '6:45 PM', '7:00 PM', '7:15 PM', '7:30 PM', '7:45 PM', '8:00 PM', '8:15 PM', '8:30 PM', '8:45 PM', '9:00 PM', '9:15 PM', '9:30 PM', '9:45 PM', '10:00 PM', '10:15 PM', '10:30 PM', '10:45 PM', '11:00 PM', '11:15 PM', '11:30 PM', '11:45 PM']
  end

  # GET /availabilities/1/edit
  def edit
    @time_select_options = ['12:00 AM', '12:15 AM', '12:30 AM', '12:45 AM', '1:00 AM', '1:15 AM', '1:30 AM', '1:45 AM', '2:00 AM', '2:15 AM', '2:30 AM', '2:45 AM', '3:00 AM', '3:15 AM', '3:30 AM', '3:45 AM', '4:00 AM', '4:15 AM', '4:30 AM', '4:45 AM', '5:00 AM', '5:15 AM', '5:30 AM', '5:45 AM', '6:00 AM', '6:15 AM', '6:30 AM', '6:45 AM', '7:00 AM', '7:15 AM', '7:30 AM', '7:45 AM', '8:00 AM', '8:15 AM', '8:30 AM', '8:45 AM', '9:00 AM', '9:15 AM', '9:30 AM', '9:45 AM', '10:00 AM', '10:15 AM', '10:30 AM', '10:45 AM', '11:00 AM', '11:15 AM', '11:30 AM', '11:45 AM', '12:00 PM', '12:15 PM', '12:30 PM', '12:45 PM', '1:00 PM', '1:15 PM', '1:30 PM', '1:45 PM', '2:00 PM', '2:15 PM', '2:30 PM', '2:45 PM', '3:00 PM', '3:15 PM', '3:30 PM', '3:45 PM', '4:00 PM', '4:15 PM', '4:30 PM', '4:45 PM', '5:00 PM', '5:15 PM', '5:30 PM', '5:45 PM', '6:00 PM', '6:15 PM', '6:30 PM', '6:45 PM', '7:00 PM', '7:15 PM', '7:30 PM', '7:45 PM', '8:00 PM', '8:15 PM', '8:30 PM', '8:45 PM', '9:00 PM', '9:15 PM', '9:30 PM', '9:45 PM', '10:00 PM', '10:15 PM', '10:30 PM', '10:45 PM', '11:00 PM', '11:15 PM', '11:30 PM', '11:45 PM']
  end

  # POST /availabilities
  # POST /availabilities.json
  def create
    @availability = Availability.new(availability_params)
    @availability.user_id = current_user.id
    if(availability_params.has_key?(:group_id))
      @availability.group_id = params[:availability][:group_id]
    else
      @availability.group_id = current_user.groups.first.id
    end

    @availability.start_date = Chronic.parse(params[:availability][:start_date])
    respond_to do |format|
      if @availability.save
        format.html { redirect_to dashboard_url, notice: 'Your split has been added.' }
        format.json { render :show, status: :created, location: @availability }
      else
        format.html { render :new }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /availabilities/1
  # PATCH/PUT /availabilities/1.json
  def update
    respond_to do |format|
      if @availability.update(availability_params)
        format.html { redirect_to dashboard_url, notice: 'Availability was successfully updated.' }
        format.json { render :show, status: :ok, location: @availability }
      else
        format.html { render :edit }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /availabilities/1
  # DELETE /availabilities/1.json
  def destroy
    @availability.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_url, notice: 'Availability was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_availability
      @availability = Availability.find(params[:id])
    end

    def authenticate_group_user
      if !current_user.groups.pluck(:id).include? @availability.group_id
        redirect_to dashboard_path, error: 'You are not in that group.'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def availability_params
      params.require(:availability).permit(:start_date, :start_time, :end_time, :user_id, :location, :location_address, :activity, :notes, :group_id)
    end
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/views/availabilities/_availability_item.html.erb
<div class="splitItem">
  <div class="splitItemContent">
    <%= image_tag(image_url(availability.user.photo(:thumb)), class: 'splitImage') %>
    <div>
      <p style="font-weight: 600"><%= availability.user.id === current_user.id ? "Me" : availability.user.first_name %></p>
      <p><%= availability.activity %></p>
      <p>Group: <%= availability.group.name %></p>
      <!-- <p><%#= availability.location_address %></p> -->
      <p><%= availability.start_time.strftime('%l:%M %P') %> - <%= availability.end_time.strftime('%l:%M %P') %></p>
    </div>
    <div class="splitItemBtnSection">
      <%# @credits = ((availability.end_time.to_i/3600)-(availability.start_time.to_i/3600)) %>
      <!-- <p style=""><%#= @credits %> <%#= @credits === 1 ? 'CREDIT' : 'CREDITS' %></p> -->
        <% if availability.user_id === current_user.id %>
          <%= link_to('Edit', edit_availability_path(availability), class: 'btnSecondarySmall') %>
        <% else %>
          <%= link_to('View', availability_path(availability), class: 'btnPrimary btnPrimarySmall') %>
        <% end %>
    </div>
  </div>
</div>

app/views/availabilities/_form.html.erb
<div class="formStandard">
  <%= form_for(availability) do |f| %>
    <% if availability.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(availability.errors.count, "error") %> prohibited this availability from being saved:</h2>

        <ul>
        <% availability.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label 'ACTIVITY (ex: science, reading out loud, handwriting, art)', class: 'labelStandard' %>
      <%= f.text_field :activity, class: 'inputStandard', required: true %>
    </div>

    <div class="field">
      <%= f.label 'DATE', class: 'labelStandard' %>
      <%= f.text_field :start_date, data:{ provide:'datepicker' },:readonly => true, class: 'inputStandard', required: true %>
    </div>

    <!-- <div class="field">
      <%#= f.label 'START TIME', class: 'labelStandard' %>
      <%#= f.select :start_time, @time_select_options, class: 'inputStandard' %>
    </div> -->
    <div class="field">
      <%= f.label 'START TIME', class: 'labelStandard' %>
      <div><%= f.time_select :start_time, class: 'inputStandard', minute_step: 15 %></div>
    </div>

    <div class="field">
      <%= f.label 'END TIME', class: 'labelStandard' %>
      <div><%= f.time_select :end_time, class: 'inputStandard', minute_step: 15 %></div>
    </div>

    <div class="field">
      <%= f.label 'LOCATION', class: 'labelStandard' %>

      <div class="radioButtonSection">
        <input type="radio" name="location" id="myHouse" value="My House">My House
      </div>
      <% if current_user.facetime != nil  && current_user.facetime.length > 2 %>
        <div class="radioButtonSection">
          <input type="radio" name="location" id="tbd" value="<%= current_user.facetime %>">Facetime: <%= current_user.facetime %>
        </div>
      <% end %>
      <% if current_user.skype != nil  && current_user.skype.length > 2 %>
        <div class="radioButtonSection">
          <input type="radio" name="location" id="tbd" value="<%= current_user.skype %>">Skype: <%= current_user.skype %>
        </div>
      <% end %>
      <% if current_user.zoom != nil  && current_user.zoom.length > 2 %>
        <div class="radioButtonSection">
          <input type="radio" name="location" id="tbd" value="<%= current_user.zoom %>">Zoom: <%= current_user.zoom %>
        </div>
      <% end %>
      <% if current_user.hangouts != nil  && current_user.hangouts.length > 2 %>
        <div class="radioButtonSection">
          <input type="radio" name="location" id="tbd" value="<%= current_user.hangouts %>">Google Hangouts: <%= current_user.hangouts %>
        </div>
      <% end %>

      <div class="radioButtonSection">
        <input type="radio" name="location" id="location1" value="">Virtual (for example: Skype : erinbrown237)
      </div>
      <div id="hiddenLocationFieldContainer" style="display:none;">
        <%= f.text_field :location, class: 'inputStandard', id:"hiddenLocationField" %>
      </div>

    </div>

      <%#= f.text_field :location_address, class: 'inputStandard' %>

    <% if current_user.groups.length > 1 %>
      <div class="field">
        <%= f.label 'GROUP', class: 'labelStandard' %>
        <%= collection_select(:availability, :group_id, current_user.groups,
                  :id, :name,
                 {:prompt => 'Select  a group', required: true, style: "width: 100%;"}) %>
      </div>
    <% end %>

    <div class="field">
      <%= f.label 'NOTES (OPTIONAL)', class: 'labelStandard' %>
      <%= f.text_field :notes, class: 'inputStandard' %>
    </div>

    <div class="actions">
      <%= f.submit 'Submit', class: 'btnPrimary btnPrimaryLarge' %>
    </div>
  <% end %>
</div>

app/views/availabilities/_split_item.html.erb
<div class="splitItem">
  <% if split.approved != true %>
    <div class="splitItemApprovalBanner">
      <h3>WAITING ON <%= split.user_id === current_user.id ? "" : "YOUR"%> APPROVAL</h3>
    </div>
  <% end %>
  <div class="splitItemContent">
    <%= image_tag(image_url(split.availability.user.photo(:thumb)), class: 'splitImage') %>
    <div>
      <p style="font-weight: 600"><%= split.availability.user.id === current_user.id ? "Me" : split.availability.user.first_name %></p>
      <p><%= split.availability.activity %></p>
      <!-- <p><%#= split.availability.location_address %></p> -->
      <p><%= split.availability.start_time.strftime('%l:%M %P') %> - <%= split.availability.end_time.strftime('%l:%M %P') %></p>
    </div>
    <div class="splitItemBtnSection">
      <% @credits = ((split.availability.end_time.to_i/3600)-(split.availability.start_time.to_i/3600)) %>
      <p style=""><%= @credits %> <%= @credits === 1 ? 'CREDIT' : 'CREDITS' %></p>
        <% if (split.availability.user_id === current_user.id) && !split.approved && !split.cancelled %>
            <%= link_to('Approve', approve_split_path(split), class: 'btnPrimary btnPrimarySmall', style:"margin-bottom: 2px;") %>
            <%= link_to('Decline', decline_split_path(split), class: 'btnSecondarySmall') %>
        <% else %>
          <%= link_to('View', split_path(split), class: 'btnPrimary btnPrimarySmall') %>
        <% end %>
    </div>
  </div>
</div>

app/views/availabilities/edit.html.erb
<div class="pageContainer">
<h2 class="signUpHeader">Edit Availability</h2>

<%= render 'form', availability: @availability %>
<% if @availability.user === current_user %>
  <div class="formStandard">

    <div class="actions">
      <%= link_to 'Cancel', @availability, method: :delete, data: { confirm: 'Are you sure you want to cancel this split?' }, class: 'btnSecondary btnSecondaryLarge', style: 'height: 30px; width: 310px; max-width: 100%' %>
    </div>
  </div>
<% end %>
</div>
<%#= link_to 'Show', @availability %> |
<%#= link_to 'Back', availabilities_path %>

app/views/availabilities/index.html.erb
<h1>My Availabilities</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @availabilities.each do |availability| %>
      <tr>
        <td><%= availability.start_time %></td>
        <td><%= availability.end_time %></td>
        <td><%= availability.user %></td>
        <td><%= link_to 'Show', availability %></td>
        <td><%= link_to 'Edit', edit_availability_path(availability) %></td>
        <td><%= link_to 'Destroy', availability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Availability', new_availability_path %>

app/views/availabilities/new.html.erb
<h1>New Availability</h1>

<%= render 'form', availability: @availability %>

app/views/availabilities/show.html.erb
<div id="chooseChildrenPopUp" style="display:none;">
  <div class="popUpContainer">
  <%= form_tag({:action => 'request_split', :controller=>"splits"}) do %>
      <div class="popUpHeader">
        <h1 class="cabinText">REQUEST SPLIT</h1>
        <%= image_tag('closeThick.svg', id: 'closeChildrenPopUp') %>
      </div>
      <div class="popUpContent">
        <h3 class="popUpInstructions">Please select children who will attend:</h3>
        <% @children.each do |child| %>
          <div class="checkBoxSection">
            <%= check_box('child', child.id, {}, true, false) %>
            <h3 class="checkBoxLabel"><%= child.first_name %></h3>
          </div>
        <% end %>
      </div>
      <%= hidden_field(:availability, :id, value: @availability.id) %>

    <div class="actions" style="margin: 15px;">
        <h3 class="btnSecondary" id="cancelChildrenPopUp">Cancel</h3>
        <%= submit_tag "Request", class: 'btnPrimary btnSubmit' %>
    </div>
  <% end %>
  </div>
</div>

<div class="formStandard">
  <div class="splitHeader">
    <div class="splitImageSection">
      <%= image_tag(image_url(@availability.user.photo(:thumb)), class: 'splitImage') %>
      <h3><%= formatUserName(@availability.user) %></h3>
    </div>
    <div>
      <!-- <%#= @credits %> CREDITS -->
    </div>
  </div>
  <div class="splitInfo">
    <h3 class="labelStandard">DATE</h3>
    <h3><%= @availability.start_date.strftime('%d/%m/%Y') %></h3>
  </div>
  <div class="splitInfo">
    <h3 class="labelStandard">START TIME</h3>
    <h3><%= @availability.start_time.strftime('%l:%M %p') %></h3>
  </div>
  <div class="splitInfo">
    <h3 class="labelStandard">END TIME</h3>
    <h3><%= @availability.end_time.strftime('%l:%M %p') %></h3>
  </div>
  <div class="splitInfo">
    <h3 class="labelStandard">ACTIVITY</h3>
    <h3><%= @availability.activity %></h3>
  </div>
  <div class="splitInfo">
    <h3 class="labelStandard">NOTES</h3>
    <h3><%= @availability.activity %></h3>
  </div>
  <div class="splitInfo">
    <h3 class="labelStandard">LOCATION</h3>
    <h3><%= @availability.location %></h3>
    <h3><%= @availability.location_address %></h3>
  </div>
  <div class="actions">
    <% if @availability.user === current_user %>
      <%= link_to 'Edit', edit_availability_path(@availability), class: "btnPrimary btnPrimaryLarge" %>
      <%= link_to 'Cancel Split', edit_availability_path(@availability), class: "btnSecondarySmall" %>
    <%# elsif @credits > current_user.credits  %>
      <!-- <div class="alert alert-error" style="text-align: center;">Not Enough Credits to Book</div> -->
    <% elsif @availability.splits.count === 0  %>
      <h3 class="btnPrimary btnPrimaryLarge" id="request-split">Request</h3 >
    <% end %>
  </div>
</div>

<script>
  $('#request-split, #closeChildrenPopUp, #cancelChildrenPopUp').bind('click', function(e) {
    console.log('click')
    e.preventDefault();
    $('#chooseChildrenPopUp').toggle();
  })
</script>